/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelinesRouteImport } from './routes/timelines'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ContributorRouteImport } from './routes/contributor'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TimelineIdRouteImport } from './routes/timeline.$id'
import { Route as PrebuiltFileRouteImport } from './routes/prebuilt.$file'

const TimelinesRoute = TimelinesRouteImport.update({
  id: '/timelines',
  path: '/timelines',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorRoute = ContributorRouteImport.update({
  id: '/contributor',
  path: '/contributor',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineIdRoute = TimelineIdRouteImport.update({
  id: '/timeline/$id',
  path: '/timeline/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrebuiltFileRoute = PrebuiltFileRouteImport.update({
  id: '/prebuilt/$file',
  path: '/prebuilt/$file',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contributor': typeof ContributorRoute
  '/reset-password': typeof ResetPasswordRoute
  '/timelines': typeof TimelinesRoute
  '/prebuilt/$file': typeof PrebuiltFileRoute
  '/timeline/$id': typeof TimelineIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contributor': typeof ContributorRoute
  '/reset-password': typeof ResetPasswordRoute
  '/timelines': typeof TimelinesRoute
  '/prebuilt/$file': typeof PrebuiltFileRoute
  '/timeline/$id': typeof TimelineIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contributor': typeof ContributorRoute
  '/reset-password': typeof ResetPasswordRoute
  '/timelines': typeof TimelinesRoute
  '/prebuilt/$file': typeof PrebuiltFileRoute
  '/timeline/$id': typeof TimelineIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contributor'
    | '/reset-password'
    | '/timelines'
    | '/prebuilt/$file'
    | '/timeline/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contributor'
    | '/reset-password'
    | '/timelines'
    | '/prebuilt/$file'
    | '/timeline/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contributor'
    | '/reset-password'
    | '/timelines'
    | '/prebuilt/$file'
    | '/timeline/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContributorRoute: typeof ContributorRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TimelinesRoute: typeof TimelinesRoute
  PrebuiltFileRoute: typeof PrebuiltFileRoute
  TimelineIdRoute: typeof TimelineIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timelines': {
      id: '/timelines'
      path: '/timelines'
      fullPath: '/timelines'
      preLoaderRoute: typeof TimelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributor': {
      id: '/contributor'
      path: '/contributor'
      fullPath: '/contributor'
      preLoaderRoute: typeof ContributorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline/$id': {
      id: '/timeline/$id'
      path: '/timeline/$id'
      fullPath: '/timeline/$id'
      preLoaderRoute: typeof TimelineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prebuilt/$file': {
      id: '/prebuilt/$file'
      path: '/prebuilt/$file'
      fullPath: '/prebuilt/$file'
      preLoaderRoute: typeof PrebuiltFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContributorRoute: ContributorRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TimelinesRoute: TimelinesRoute,
  PrebuiltFileRoute: PrebuiltFileRoute,
  TimelineIdRoute: TimelineIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
